name: Deploy via FTP
on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v3
    
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        # 🛡️ BLINDAJE DE PRODUCCIÓN (Regla de ORO)
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          .env
          brokers/.env
          BackUp/**
          *.zip
          *.sql
          knowledge/**
          # Protegemos los archivos físicos de las Inmobiliarias
          public_html/companies/**
          # Protegemos las sesiones y logs del servidor
          brokers/storage/logs/**
          brokers/storage/framework/cache/**
          brokers/storage/framework/sessions/**
          brokers/storage/framework/views/**